### ISSUE TITLE
Normalise grids properly

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pinecards#76]
Two-dimensional distributions are not supported by `mg5_aMC`, and therefore we linearise the 2D distributions to 1D, but after the grid generation we have to undo the linearisation using `pineappl remap ...` in a `postrun.sh` script to properly normalise them. The following analyses are affected by this:

- [x] ATLAS_DY3D_8TEV, fixed in commit 739ab7fe9c3ed10f8a11667acc56f65fa7499118, but needs implementation in PineAPPL
- [x] CMSDY2D11, fixed in commit 8e38d71e6bb2958ea6e3563361cdc57dc1b1dc8c
- [x] ~~#43: CMSDY2D12~~
- [x] #44: ATLAS_DY2D_8TEV
- [x] #67: CMS_2JET_7TEV, fixed in commit be0afb77db15e55de8640c151f7dd7fc75c206f2
- [x] #69: ATLAS_2JET_7TEV_R06, fixed in commits be0afb77db15e55de8640c151f7dd7fc75c206f2 and 883f58e7ef58fd4927364b175481cc1f8b8a1bad
- [x] #70: CMS_2JET_3D_8TEV, fixed in commit be0afb77db15e55de8640c151f7dd7fc75c206f2, but needs implementation in PineAPPL
- [x] #71: ATLAS_1JET_8TEV_R06, fixed in commit 0cca8bacd3d1c7b2dc5206728964f5c7f55eae70
